### ISSUE TITLE
Android Errors Out on Front Camera Landscape

### ISSUE THREAD

**Issue by kstokes-asco** [edufolly/flutter_mobile_vision#16]
I'm running the package on a Lenovo tablet and using the barcode scanning feature. I am using the front camera and noticed that when the tablet is in landscape mode with the front camera at the top of the device the app errors out when scanning with the following in the debug console:

`W/DynamiteModule(22489): Local module descriptor class for com.google.android.gms.vision.dynamite not found.
I/DynamiteModule(22489): Considering local module com.google.android.gms.vision.dynamite:0 and remote module com.google.android.gms.vision.dynamite:1800
I/DynamiteModule(22489): Selected remote version of com.google.android.gms.vision.dynamite, version >= 1800
I/Vision  (22489): Loading library libbarhopper.so
I/Vision  (22489): libbarhopper.so library load status: true
D/AndroidRuntime(22489): Shutting down VM
E/AndroidRuntime(22489): FATAL EXCEPTION: main
E/AndroidRuntime(22489): Process: com.example.billoflading, PID: 22489
E/AndroidRuntime(22489): java.lang.RuntimeException: set display orientation failed
E/AndroidRuntime(22489): 	at android.hardware.Camera.setDisplayOrientation(Native Method)
E/AndroidRuntime(22489): 	at io.github.edufolly.fluttermobilevision.ui.CameraSource.setRotation(CameraSource.java:1032)
E/AndroidRuntime(22489): 	at io.github.edufolly.fluttermobilevision.ui.CameraSource.createCamera(CameraSource.java:784)
E/AndroidRuntime(22489): 	at io.github.edufolly.fluttermobilevision.ui.CameraSource.start(CameraSource.java:384)
E/AndroidRuntime(22489): 	at io.github.edufolly.fluttermobilevision.ui.CameraSourcePreview.startIfReady(CameraSourcePreview.java:97)
E/AndroidRuntime(22489): 	at io.github.edufolly.fluttermobilevision.ui.CameraSourcePreview.access$200(CameraSourcePreview.java:35)
E/AndroidRuntime(22489): 	at io.github.edufolly.fluttermobilevision.ui.CameraSourcePreview$SurfaceCallback.surfaceCreated(CameraSourcePreview.java:121)
E/AndroidRuntime(22489): 	at android.view.SurfaceView.updateWindow(SurfaceView.java:632)
E/AndroidRuntime(22489): 	at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:162)
E/AndroidRuntime(22489): 	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
E/AndroidRuntime(22489): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2205)
E/AndroidRuntime(22489): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
E/AndroidRuntime(22489): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6343)
E/AndroidRuntime(22489): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
E/AndroidRuntime(22489): 	at android.view.Choreographer.doCallbacks(Choreographer.java:686)
E/AndroidRuntime(22489): 	at android.view.Choreographer.doFrame(Choreographer.java:621)
E/AndroidRuntime(22489): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
E/AndroidRuntime(22489): 	at android.os.Handler.handleCallback(Handler.java:751)
E/AndroidRuntime(22489): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(22489): 	at android.os.Looper.loop(Looper.java:154)
E/AndroidRuntime(22489): 	at android.app.ActivityThread.main(ActivityThread.java:6119)
E/AndroidRuntime(22489): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(22489): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
E/AndroidRuntime(22489): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)`

This doesn't happen when using the back camera, or when using any other orientation with the front camera. For example, when scanning with the front camera in landscape mode and the camera at the bottom of the tablet, it does not error out. 

Any ideas?

**Comment by kstokes-asco** [comment]
![services](https://user-images.githubusercontent.com/41705251/50105244-2ecab880-01fa-11e9-80e9-6e7f0b1eec0b.jpeg)

I'm not entirely sure that made a difference. Any other ideas? I updated the plugin from 0.1.1 to 0.1.2

**Comment by edufolly** [comment]
Hi @kstokes-asco,

any update about this issue?

**Comment by edufolly** [comment]
I've just published a new demo app. Check it out... [Flutter Mobile Vision Start](https://github.com/edufolly/flutter_mobile_vision_start)

Please feel free to ask for further help here.
