### ISSUE TITLE
GraphicOverlay.java uses unchecked or unsafe operations

### ISSUE THREAD

**Issue by artob** [edufolly/flutter_mobile_vision#18]
After adding this package to a Flutter project, `flutter run` outputs `-Xlint:deprecation` and `-Xlint:unchecked` warnings from the Java compilation:

    $ flutter run
    Launching lib/main.dart on Android SDK built for x86 in debug mode...
    Initializing gradle...                                       4.9s
    Resolving dependencies...                                    3.3s
    Running 'gradlew assembleDebug'...                               
    Note: Some input files use or override a deprecated API.
    Note: Recompile with -Xlint:deprecation for details.
    Note: ~/.pub-cache/hosted/pub.dartlang.org/flutter_mobile_vision-0.1.1/android/src/main/java/io/github/edufolly/fluttermobilevision/ui/GraphicOverlay.java uses unchecked or unsafe operations.
    Note: Recompile with -Xlint:unchecked for details.
    Built build/app/outputs/apk/debug/app-debug.apk.
    Installing build/app/outputs/apk/app.apk...                  3.4s
    Syncing files to device Android SDK built for x86...             

Ideally, these complaints could be fixed or at least silenced such that the new user experience for this package doesn't raise undue concerns and red flags.

**Comment by edufolly** [comment]
How we could do this? Maybe a pull request helps.

**Comment by artob** [comment]
@edufolly I've submitted a PR to silence these warnings. It's a single-line change to the source file in question.
