### ISSUE TITLE
Suppress a package UI to make use of my own UI

### ISSUE THREAD

**Issue by Intellugo** [edufolly/flutter_mobile_vision#19]
Basically, I want to use the Flutter mobile packages https://pub.dartlang.org/packages/flutter_mobile_vision#-readme-tab- without utilizing there UI interface provided. I mean a simple example pops up a UI associated with the package, I would like to suppress this so I can build my own UI on top of it.

**Comment by edufolly** [comment]
Hi @Intellugo,
the plugin is about the integration with the Mobile Vision package, you can use your own UI.
The provided example is only a guide to follow.
