### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by ghost** [edufolly/flutter_mobile_vision#2]
It would be cool to our the text , Google translate it and reconstitute it back on the image.

Not easy because the text length will change. I think the ocr API gives back the text box dimensions. Not sure how to calculate the dimensions of the translated text. It can probably be gotten at the dart layer though.
Dart libs for doing the image compositing are pretty good now I think.

Anyway just an idea I had...

**Comment by edufolly** [comment]
It's a great idea. Maybe you can use [Google Goggles](https://play.google.com/store/apps/details?id=com.google.android.apps.unveil) to do this, or this is a spark to create a translation plugin.

**Comment by gedw99** [comment]
i prefer to make a translation plugin.  Would be pretty easy.

but i just wanted to highligh the user case that i though of. Just thought it woudl be useful.
