### ISSUE TITLE
Does this package supports android 6?

### ISSUE THREAD

**Issue by raziAkbar** [edufolly/flutter_mobile_vision#20]
I tried using the application with my phone with android 6 it doesn't open camera and say unable to recognize but it is working with android version 7. Can you guide me for its solution.

**Comment by edufolly** [comment]
Works great on Android 6. I developed using a Motorola phone with Android 6. If possible, send the stack trace.

**Comment by raziAkbar** [comment]
Whereas i have given the camera permission

**Comment by raziAkbar** [comment]
I/flutter (21159): SystemChrome.setApplicationSwitcherDescription
I/Timeline(21159): Timeline: Activity_idle id: android.os.BinderProxy@56f23ec time:36022533
I/flutter (21159): SystemChrome.setSystemUIOverlayStyle
D/ViewRootImpl(21159): ViewPostImeInputStage processPointer 0
D/ViewRootImpl(21159): ViewPostImeInputStage processPointer 1
I/flutter (21159): SystemSound.play
I/[MALI][Gralloc](21159): [+]r_hnd(0x9c420880), client(55), share_fd(68)
D/GraphicBuffer(21159): register, handle(0x9c420880) (w:540 h:960 s:544 f:0x1 u:0x000b00)
D/ViewRootImpl(21159): ViewPostImeInputStage processPointer 0
D/ViewRootImpl(21159): ViewPostImeInputStage processPointer 1
I/flutter (21159): SystemSound.play
I/Timeline(21159): Timeline: Activity_launch_request id:io.github.edufolly.fluttermobilevisionexample time:36032687
W/DynamiteModule(21159): Local module descriptor class for com.google.android.gms.vision.dynamite not found.
I/DynamiteModule(21159): Considering local module com.google.android.gms.vision.dynamite:0 and remote module com.google.android.gms.vision.dynamite:1800
I/DynamiteModule(21159): Selected remote version of com.google.android.gms.vision.dynamite, version >= 1800
I/Vision  (21159): Loading library libocr.so
I/Vision  (21159): libocr.so library load status: false
W/TextNativeHandle(21159): Native handle not yet available. Reverting to no-op handle.
W/DynamiteModule(21159): Local module descriptor class for com.google.android.gms.vision.dynamite not found.
I/DynamiteModule(21159): Considering local module com.google.android.gms.vision.dynamite:0 and remote module com.google.android.gms.vision.dynamite:1800
I/DynamiteModule(21159): Selected remote version of com.google.android.gms.vision.dynamite, version >= 1800
I/Vision  (21159): Loading library libocr.so
I/Vision  (21159): libocr.so library load status: false
I/Timeline(21159): Timeline: Activity_idle id: android.os.BinderProxy@56f23ec time:36032760
I/flutter (21159): Error: PlatformException(Intent is null (the camera permission may not be granted), null, null)
I/flutter (21159): SystemChrome.setApplicationSwitcherDescription
V/ActivityThread(21159): updateVisibility : ActivityRecord{d65ca4a token=android.os.BinderProxy@56f23ec {io.github.edufolly.fluttermobilevisionexample/io.github.edufolly.fluttermobilevisionexample.MainActivity}} show : true
I/Timeline(21159): Timeline: Activity_idle id: android.os.BinderProxy@56f23ec time:36195762
D/Surface (21159): Surface::disconnect(this=0xae1b8200,api=1)
D/GraphicBuffer(21159): unregister, handle(0xb30b63c0) (w:540 h:960 s:544 f:0x1 u:0x000b00)
I/[MALI][Gralloc](21159): [-]r_hnd(0xb30b63c0), client(55), share_fd(57)
D/GraphicBuffer(21159): unregister, handle(0xb30b6dc0) (w:540 h:960 s:544 f:0x1 u:0x000b00)
I/[MALI][Gralloc](21159): [-]r_hnd(0xb30b6dc0), client(55), share_fd(61)
D/GraphicBuffer(21159): unregister, handle(0x9c420880) (w:540 h:960 s:544 f:0x1 u:0x000b00)
I/[MALI][Gralloc](21159): [-]r_hnd(0x9c420880), client(55), share_fd(68)
D/Surface (21159): Surface::disconnect(this=0xae1b7400,api=1)
D/GraphicBuffer(21159): unregister, handle(0xb30b6820) (w:540 h:960 s:544 f:0x1 u:0x000b00)
I/[MALI][Gralloc](21159): [-]r_hnd(0xb30b6820), client(55), share_fd(54)
D/GraphicBuffer(21159): unregister, handle(0xb30b6960) (w:540 h:960 s:544 f:0x1 u:0x000b00)
I/[MALI][Gralloc](21159): [-]r_hnd(0xb30b6960), client(55), share_fd(60)
V/ActivityThread(21159): updateVisibility : ActivityRecord{d65ca4a token=android.os.BinderProxy@56f23ec {io.github.edufolly.fluttermobilevisionexample/io.github.edufolly.fluttermobilevisionexample.MainActivity}} show : false

**Comment by edufolly** [comment]
Hi @raziAkbar,

try to "clear data" of the Google Play Service app, so the Mobile Vision pack will be download again.
#12
