### ISSUE TITLE
Filed to install Package

### ISSUE THREAD

**Issue by renanserrou** [edufolly/flutter_mobile_vision#37]
Failed to reinstall 1 package:
- flutter_mobile_vision 0.1.3
pub finished with exit code 69

I was getting some issues so I didi a cache repair and got this, any ideas?

**Comment by edufolly** [comment]
Hi @renanserrou,

try to review your ```pubscep.yaml``` file. Maybe clean your project with ```flutter clean```. In the last case, delete ```~/.pub-cache``` folder.

If it doesn't work, please submit more information.

**Comment by edufolly** [comment]
I've just published a new demo app. Check it out... [Flutter Mobile Vision Start](https://github.com/edufolly/flutter_mobile_vision_start)
