### ISSUE TITLE
Failed to run debug mode after install package

### ISSUE THREAD

**Issue by akimond991022** [edufolly/flutter_mobile_vision#38]
I've installed flutter_mobile_vision: 0.1.3.
I run 'package get'.
And then I get these errors while running.

C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_mobile_vision-0.1.3\android\src\main\java\io\github\edufolly\fluttermobilevision\util\AbstractCaptureActivity.java:9: error: cannot find symbol
import android.support.v4.app.ActivityCompat;
                             ^
  symbol:   class ActivityCompat
  location: package android.support.v4.app
C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_mobile_vision-0.1.3\android\src\main\java\io\github\edufolly\fluttermobilevision\barcode\BarcodeUpdateListener.java:3: error: package android.support.annotation does not exist
import android.support.annotation.UiThread;
                                 ^
C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_mobile_vision-0.1.3\android\src\main\java\io\github\edufolly\fluttermobilevision\ui\CameraSource.java:28: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
                                 ^
C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_mobile_vision-0.1.3\android\src\main\java\io\github\edufolly\fluttermobilevision\ui\CameraSource.java:29: error: package android.support.annotation does not exist
import android.support.annotation.RequiresPermission;
                                 ^
C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_mobile_vision-0.1.3\android\src\main\java\io\github\edufolly\fluttermobilevision\ui\CameraSource.java:30: error: package android.support.annotation does not exist
import android.support.annotation.StringDef;
                                 ^
C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_mobile_vision-0.1.3\android\src\main\java\io\github\edufolly\fluttermobilevision\ui\CameraSourcePreview.java:22: error: package android.support.annotation does not exist
import android.support.annotation.RequiresPermission;
                                 ^
C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_mobile_vision-0.1.3\android\src\main\java\io\github\edufolly\fluttermobilevision\FlutterMobileVisionPlugin.java:8: error: cannot find symbol
import android.support.v4.app.ActivityCompat;
                             ^
  symbol:   class ActivityCompat
  location: package android.support.v4.app
C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_mobile_vision-0.1.3\android\src\main\java\io\github\edufolly\fluttermobilevision\FlutterMobileVisionPlugin.java:9: error: package android.support.v4.content does not exist
import android.support.v4.content.ContextCompat;
                                 ^
C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_mobile_vision-0.1.3\android\src\main\java\io\github\edufolly\fluttermobilevision\ui\CameraSource.java:147: error: cannot find symbol
    @StringDef({
     ^
  symbol:   class StringDef
  location: class CameraSource
C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_mobile_vision-0.1.3\android\src\main\java\io\github\edufolly\fluttermobilevision\ui\CameraSource.java:160: error: cannot find symbol
    @StringDef({
     ^
  symbol:   class StringDef
  location: class CameraSource
C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_mobile_vision-0.1.3\android\src\main\java\io\github\edufolly\fluttermobilevision\barcode\BarcodeUpdateListener.java:9: error: cannot find symbol
    @UiThread
     ^
  symbol:   class UiThread
  location: interface BarcodeUpdateListener
C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_mobile_vision-0.1.3\android\src\main\java\io\github\edufolly\fluttermobilevision\ui\CameraSource.java:344: error: cannot find symbol
    @RequiresPermission(Manifest.permission.CAMERA)
     ^
  symbol:   class RequiresPermission
  location: class CameraSource
C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_mobile_vision-0.1.3\android\src\main\java\io\github\edufolly\fluttermobilevision\ui\CameraSource.java:379: error: cannot find symbol
    @RequiresPermission(Manifest.permission.CAMERA)
     ^
  symbol:   class RequiresPermission
  location: class CameraSource
C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_mobile_vision-0.1.3\android\src\main\java\io\github\edufolly\fluttermobilevision\ui\CameraSource.java:534: error: cannot find symbol
    @Nullable
     ^
  symbol:   class Nullable
  location: class CameraSource
C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_mobile_vision-0.1.3\android\src\main\java\io\github\edufolly\fluttermobilevision\ui\CameraSource.java:574: error: cannot find symbol
    @Nullable
     ^
  symbol:   class Nullable
  location: class CameraSource
C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_mobile_vision-0.1.3\android\src\main\java\io\github\edufolly\fluttermobilevision\ui\CameraSource.java:622: error: cannot find symbol
    public void autoFocus(@Nullable AutoFocusCallback cb) {
                           ^
  symbol:   class Nullable
  location: class CameraSource
C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_mobile_vision-0.1.3\android\src\main\java\io\github\edufolly\fluttermobilevision\ui\CameraSource.java:659: error: cannot find symbol
    public boolean setAutoFocusMoveCallback(@Nullable AutoFocusMoveCallback cb) {
                                             ^
  symbol:   class Nullable
  location: class CameraSource
C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_mobile_vision-0.1.3\android\src\main\java\io\github\edufolly\fluttermobilevision\ui\CameraSourcePreview.java:57: error: cannot find symbol
    @RequiresPermission(Manifest.permission.CAMERA)
     ^
  symbol:   class RequiresPermission
  location: class CameraSourcePreview
C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_mobile_vision-0.1.3\android\src\main\java\io\github\edufolly\fluttermobilevision\ui\CameraSourcePreview.java:73: error: cannot find symbol
    @RequiresPermission(Manifest.permission.CAMERA)
     ^
  symbol:   class RequiresPermission
  location: class CameraSourcePreview
C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_mobile_vision-0.1.3\android\src\main\java\io\github\edufolly\fluttermobilevision\ui\CameraSourcePreview.java:94: error: cannot find symbol
    @RequiresPermission(Manifest.permission.CAMERA)
     ^
  symbol:   class RequiresPermission
  location: class CameraSourcePreview
C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_mobile_vision-0.1.3\android\src\main\java\io\github\edufolly\fluttermobilevision\util\AbstractCaptureActivity.java:83: error: cannot find symbol
            int rc = ActivityCompat.checkSelfPermission(this, Manifest.permission.CAMERA);
                     ^
  symbol:   variable ActivityCompat
  location: class AbstractCaptureActivity<T>
  where T is a type-variable:
    T extends Graphic declared in class AbstractCaptureActivity
C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_mobile_vision-0.1.3\android\src\main\java\io\github\edufolly\fluttermobilevision\FlutterMobileVisionPlugin.java:149: error: cannot find symbol
                if (ContextCompat.checkSelfPermission(registrar.activity(),
                    ^
  symbol:   variable ContextCompat
  location: class FlutterMobileVisionPlugin
C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_mobile_vision-0.1.3\android\src\main\java\io\github\edufolly\fluttermobilevision\FlutterMobileVisionPlugin.java:153: error: cannot find symbol
                    ActivityCompat.requestPermissions(registrar.activity(),
                    ^
  symbol:   variable ActivityCompat
  location: class FlutterMobileVisionPlugin
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
23 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_mobile_vision:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13s
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by edufolly** [comment]
Hi @akimond991022,

edit ```android/gradle.properties``` and add these lines:

```
android.enableJetifier=true
android.useAndroidX=true
``` 

I've just published a new demo app. Check it out... [Flutter Mobile Vision Start](https://github.com/edufolly/flutter_mobile_vision_start)

**Comment by klaszlo8207** [comment]
Please reopen, this issue is not fixed at all. 

In my gradle properties I have this

android.enableJetifier=true
android.useAndroidX=true
org.gradle.jvmargs=-Xmx1536M
android.enableR8=true

but I get the same
