### ISSUE TITLE
Face Recognition

### ISSUE THREAD

**Issue by NTMS2017** [edufolly/flutter_mobile_vision#4]
Hi,

Thanks for the plugin and demo. I am wondering when we can implement the Face Recognition in both iOS and android flutter app? When detected faces how to get Face coordinates as Face Recognition. and save it to sql database or firebase database? Thanks

**Comment by edufolly** [comment]
Hi @NTMS2017,

I'm not an iOS expert, and need some help to port de Mobile Vision to Apple devices. If you could help, I appreciate that.

About the coordinates, the object returned by the face method is a list of Faces.

The Face object has the following attributes:

```dart
class Face {
  final int id;
  final double eulerY;
  final double eulerZ;
  final double leftEyeOpenProbability;
  final double rightEyeOpenProbability;
  final double smilingProbability;
  final int top;
  final int bottom;
  final int left;
  final int right;
...
```

The last 4 attributes are referring to the rectangle that contains the face. You can use these values to save in any kind of database.

Hope this helps.

Best Regards.

**Comment by NTMS2017** [comment]
Hi, edufolly I don't use iPhone I am android lovers :) 

But I am using macOS high Sierra with IntelliJ. I try to test with running iPhone X 11.3 simulator and get below error. Hope this helps...

**Note:** Does the mobile vision or Flutter supports Face recognition for login? 

Launching lib/main.dart on iPhone X in debug mode...
Running pod install...
Running Xcode clean...
Starting Xcode build...
Xcode build done.
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
    
Xcode's output:
↳
    === BUILD TARGET flutter_mobile_vision OF PROJECT Pods WITH CONFIGURATION Debug ===
    In file included from /Users/niyazitoros/Desktop/IRIS_VOICE/flutter_mobile_vision-master/ios/Classes/FlutterMobileVisionPlugin.m:1:
    /Users/niyazitoros/Desktop/IRIS_VOICE/flutter_mobile_vision-master/ios/Classes/**FlutterMobileVisionPlugin.h:1:9**: fatal error: '**Flutter/Flutter.h**' file not found
    **#import <Flutter/Flutter.h>**
            ^~~~~~~~~~~~~~~~~~~
    1 error generated.
Could not build the application for the simulator.
Error launching application on iPhone X.

**Comment by edufolly** [comment]
Hi @NTMS2017 ,

the code isn't implemented for iOS yet.
