### ISSUE TITLE
App crash when scan button pressed

### ISSUE THREAD

**Issue by AbelAyalew** [edufolly/flutter_mobile_vision#49]
i build the example app and it launches but when i press the scan button the app crashs

**Comment by edufolly** [comment]
Could you send the log of the crash and `flutter doctor -v` output?

**Comment by AbelAyalew** [comment]
![image](https://user-images.githubusercontent.com/44599573/80479993-93eafe00-8958-11ea-97c6-012ce1c31eda.png)
![image](https://user-images.githubusercontent.com/44599573/80480070-b11fcc80-8958-11ea-9121-b495aa442872.png)

this are the crush log

**Comment by AbelAyalew** [comment]
![image](https://user-images.githubusercontent.com/44599573/80480152-ceed3180-8958-11ea-9a05-6bd3d63a0870.png)

and 'flutter doctor -v' output

**Comment by edufolly** [comment]
I saw an error in the plugin README.md.

I'll try to change the package name but you can use this version adding this line to `AndroidManifest.xml`:

`<activity android:name="io.github.edufolly.flutter_mobile_vision.barcode.BarcodeCaptureActivity" />`

**Comment by edufolly** [comment]
Package updated. Try to use version `0.1.4+1`. If you have further questions, please open a new issue. Thanks for your support.

**Comment by AbelAyalew** [comment]
now it works thanks!
