### ISSUE TITLE
真机调试无法调用相机

### ISSUE THREAD

**Issue by liuswong** [edufolly/flutter_mobile_vision#56]
W/DynamiteModule( 1782): Local module descriptor class for com.google.android.gms.vision.dynamite.ocr not found.
W/DynamiteModule( 1782): Failed to retrieve remote module version.
W/GooglePlayServicesUtil( 1782): Google Play Store is missing.
I/DynamiteModule( 1782): Considering local module com.google.android.gms.vision.dynamite.ocr:0 and remote module com.google.android.gms.vision.dynamite.ocr:0
W/GooglePlayServicesUtil( 1782): Google Play Store is missing.
W/DynamiteModule( 1782): Local module descriptor class for com.google.android.gms.vision.ocr not found.
I/DynamiteModule( 1782): Considering local module com.google.android.gms.vision.ocr:0 and remote module com.google.android.gms.vision.ocr:0
E/Vision  ( 1782): Error loading module com.google.android.gms.vision.ocr optional module true: com.google.android.gms.dynamite.DynamiteModule$LoadingException: No acceptable module found. Local version is 0 and remote version is 0.
I/SendBroadcastPermission( 1782): action:com.google.android.gms.vision.DEPENDENCY, mPermissionType:0
W/TextNativeHandle( 1782): Native handle not yet available. Reverting to no-op handle.
W/DynamiteModule( 1782): Local module descriptor class for com.google.android.gms.vision.dynamite.ocr not found.
W/GooglePlayServicesUtil( 1782): Google Play Store is missing.
I/DynamiteModule( 1782): Considering local module com.google.android.gms.vision.dynamite.ocr:0 and remote module com.google.android.gms.vision.dynamite.ocr:0
W/GooglePlayServicesUtil( 1782): Google Play Store is missing.
W/DynamiteModule( 1782): Local module descriptor class for com.google.android.gms.vision.ocr not found.
I/DynamiteModule( 1782): Considering local module com.google.android.gms.vision.ocr:0 and remote module com.google.android.gms.vision.ocr:0

**Comment by liuswong** [comment]
[√] Flutter (Channel stable, v1.17.3, on Microsoft Windows [Version 10.0.18363.418], locale zh-CN)
 
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Android Studio (version 4.0)
[√] VS Code (version 1.47.3)
[√] Connected device (1 available)

• No issues found!

**Comment by edufolly** [comment]
Hi @liuswong,

you need Google GMS (https://en.wikipedia.org/wiki/Google_mobile_services) in your device.

**Comment by edufolly** [comment]
If you have further questions, please reopen this issue or open a new one.

Best.
