### ISSUE TITLE
Crash when the permission is not granted on Android

### ISSUE THREAD

**Issue by g123k** [edufolly/flutter_mobile_vision#7]
Hello,

On Android, the first time the application is opened (or if the camera permission is never granted), the app will crash.

In the `onActivityResult` method, if the `resultCode` is an error, you are never checking if the intent is null. In the case where the permission is not granted, the intent is null, so the app will crash.

**Comment by edufolly** [comment]
@g123k thanks for you pull request. I'll analyze and merge as soon as possible.

**Comment by edufolly** [comment]
@g123k Merged! I'll create a fix to flutter package.

**Comment by edufolly** [comment]
Fixed in version 0.1.1
